<?php

declare(strict_types=1);

use Database\MigrationInterface;
use PDO;

return new class implements MigrationInterface {
    public function version(): string { return '002'; }
    public function timestamp(): string { return '2026-07-25T00:01:00Z'; }
    public function description(): string { return 'Create identity and authorization tables.'; }
    public function dependencies(): array { return ['001']; }
    public function up(PDO $pdo): void {
        $sql = [
            'CREATE TABLE users (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, email VARCHAR(254) NULL, phone VARCHAR(32) NULL, display_name VARCHAR(160) NOT NULL, password_hash VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT \'active\', email_verified_at DATETIME(6) NULL, phone_verified_at DATETIME(6) NULL, last_login_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, deleted_by BIGINT UNSIGNED NULL, deletion_reason VARCHAR(500) NULL, UNIQUE KEY uq_users_public_id (public_id), UNIQUE KEY uq_users_email (email), UNIQUE KEY uq_users_phone (phone), KEY idx_users_institution_status (institution_id, status), CONSTRAINT fk_users_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE roles (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(120) NOT NULL, is_system BOOLEAN NOT NULL DEFAULT FALSE, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, UNIQUE KEY uq_roles_institution_code (institution_id, code), CONSTRAINT fk_roles_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE permissions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, code VARCHAR(128) NOT NULL, name VARCHAR(160) NOT NULL, module VARCHAR(64) NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, UNIQUE KEY uq_permissions_institution_code (institution_id, code), CONSTRAINT fk_permissions_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE user_roles (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, role_id BIGINT UNSIGNED NOT NULL, starts_at DATETIME(6) NOT NULL, ends_at DATETIME(6) NULL, assigned_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, UNIQUE KEY uq_user_roles_assignment (user_id, role_id, starts_at), KEY idx_user_roles_role (role_id), CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT, CONSTRAINT fk_user_roles_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT chk_user_roles_dates CHECK (ends_at IS NULL OR ends_at > starts_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE role_permissions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, granted_at DATETIME(6) NOT NULL, granted_by BIGINT UNSIGNED NULL, UNIQUE KEY uq_role_permissions_mapping (role_id, permission_id), KEY idx_role_permissions_permission (permission_id), CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT, CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE RESTRICT, CONSTRAINT fk_role_permissions_granted_by FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE user_scopes (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, scope_type VARCHAR(32) NOT NULL, scope_reference_id BIGINT UNSIGNED NOT NULL, starts_at DATETIME(6) NOT NULL, ends_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, UNIQUE KEY uq_user_scopes_period (user_id, scope_type, scope_reference_id, starts_at), KEY idx_user_scopes_lookup (scope_type, scope_reference_id), CONSTRAINT fk_user_scopes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT chk_user_scopes_dates CHECK (ends_at IS NULL OR ends_at > starts_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE password_reset_tokens (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL, expires_at DATETIME(6) NOT NULL, used_at DATETIME(6) NULL, requested_ip VARBINARY(16) NULL, created_at DATETIME(6) NOT NULL, UNIQUE KEY uq_password_reset_tokens_hash (token_hash), KEY idx_password_reset_tokens_user_expiry (user_id, expires_at), CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE user_sessions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, session_hash CHAR(64) NOT NULL, expires_at DATETIME(6) NOT NULL, revoked_at DATETIME(6) NULL, ip_address VARBINARY(16) NULL, user_agent VARCHAR(512) NULL, created_at DATETIME(6) NOT NULL, UNIQUE KEY uq_user_sessions_hash (session_hash), KEY idx_user_sessions_user_expiry (user_id, expires_at), CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'
        ]; foreach ($sql as $statement) { $pdo->prepare($statement)->execute(); }
    }
    public function down(PDO $pdo): void { foreach (['user_sessions','password_reset_tokens','user_scopes','role_permissions','user_roles','permissions','roles','users'] as $table) { $pdo->prepare("DROP TABLE IF EXISTS {$table}")->execute(); } }
};
