<?php

declare(strict_types=1);

use Database\MigrationInterface;
use PDO;

return new class implements MigrationInterface {
    public function version(): string { return '003'; }
    public function timestamp(): string { return '2026-07-25T00:02:00Z'; }
    public function description(): string { return 'Create academic structure tables.'; }
    public function dependencies(): array { return ['002']; }
    public function up(PDO $pdo): void {
        $sql = [
            'CREATE TABLE academic_years (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, name VARCHAR(100) NOT NULL, starts_on DATE NOT NULL, ends_on DATE NOT NULL, status VARCHAR(32) NOT NULL DEFAULT \'draft\', created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, UNIQUE KEY uq_academic_years_public_id (public_id), UNIQUE KEY uq_academic_years_name (institution_id, name), CONSTRAINT fk_academic_years_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT, CONSTRAINT chk_academic_years_dates CHECK (ends_on > starts_on)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE terms (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, academic_year_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, name VARCHAR(100) NOT NULL, starts_on DATE NOT NULL, ends_on DATE NOT NULL, sequence SMALLINT UNSIGNED NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, UNIQUE KEY uq_terms_public_id (public_id), UNIQUE KEY uq_terms_year_sequence (academic_year_id, sequence), CONSTRAINT fk_terms_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT, CONSTRAINT fk_terms_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE RESTRICT, CONSTRAINT chk_terms_dates CHECK (ends_on > starts_on)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE classrooms (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, name VARCHAR(120) NOT NULL, capacity SMALLINT UNSIGNED NULL, status VARCHAR(32) NOT NULL DEFAULT \'active\', created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, UNIQUE KEY uq_classrooms_public_id (public_id), UNIQUE KEY uq_classrooms_name (institution_id, name), CONSTRAINT fk_classrooms_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT, CONSTRAINT chk_classrooms_capacity CHECK (capacity IS NULL OR capacity > 0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE classes (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, academic_year_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, name VARCHAR(120) NOT NULL, capacity SMALLINT UNSIGNED NULL, status VARCHAR(32) NOT NULL DEFAULT \'active\', created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, UNIQUE KEY uq_classes_public_id (public_id), UNIQUE KEY uq_classes_year_name (academic_year_id, name), KEY idx_classes_year_status (academic_year_id, status), CONSTRAINT fk_classes_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT, CONSTRAINT fk_classes_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE RESTRICT, CONSTRAINT chk_classes_capacity CHECK (capacity IS NULL OR capacity > 0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE schedules (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, class_id BIGINT UNSIGNED NOT NULL, academic_year_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT \'active\', created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, UNIQUE KEY uq_schedules_public_id (public_id), KEY idx_schedules_class_year (class_id, academic_year_id), CONSTRAINT fk_schedules_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT, CONSTRAINT fk_schedules_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE RESTRICT, CONSTRAINT fk_schedules_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE schedule_slots (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, schedule_id BIGINT UNSIGNED NOT NULL, classroom_id BIGINT UNSIGNED NULL, weekday TINYINT UNSIGNED NOT NULL, starts_at TIME NOT NULL, ends_at TIME NOT NULL, label VARCHAR(160) NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, UNIQUE KEY uq_schedule_slots_start (schedule_id, weekday, starts_at), KEY idx_schedule_slots_classroom (classroom_id), CONSTRAINT fk_schedule_slots_schedule FOREIGN KEY (schedule_id) REFERENCES schedules(id) ON DELETE RESTRICT, CONSTRAINT fk_schedule_slots_classroom FOREIGN KEY (classroom_id) REFERENCES classrooms(id) ON DELETE SET NULL, CONSTRAINT chk_schedule_slots_weekday CHECK (weekday BETWEEN 1 AND 7), CONSTRAINT chk_schedule_slots_times CHECK (ends_at > starts_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE holidays (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, name VARCHAR(160) NOT NULL, starts_on DATE NOT NULL, ends_on DATE NOT NULL, scope_type VARCHAR(32) NOT NULL DEFAULT \'institution\', scope_reference_id BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, UNIQUE KEY uq_holidays_public_id (public_id), KEY idx_holidays_dates (institution_id, starts_on, ends_on), CONSTRAINT fk_holidays_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT, CONSTRAINT chk_holidays_dates CHECK (ends_on >= starts_on)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'
        ]; foreach ($sql as $statement) { $pdo->prepare($statement)->execute(); }
    }
    public function down(PDO $pdo): void { foreach (['holidays','schedule_slots','schedules','classes','classrooms','terms','academic_years'] as $table) { $pdo->prepare("DROP TABLE IF EXISTS {$table}")->execute(); } }
};
