<?php

declare(strict_types=1);

use Database\MigrationInterface;
use PDO;

return new class implements MigrationInterface {
    public function version(): string { return '004'; }
    public function timestamp(): string { return '2026-07-25T00:03:00Z'; }
    public function description(): string { return 'Create student and employee foundation tables.'; }
    public function dependencies(): array { return ['003']; }
    public function up(PDO $pdo): void {
        $sql = [
            'CREATE TABLE students (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, legal_first_name VARCHAR(120) NOT NULL, legal_last_name VARCHAR(120) NOT NULL, birth_date DATE NOT NULL, gender_code VARCHAR(32) NULL, current_status VARCHAR(32) NOT NULL DEFAULT \'draft_registration\', created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, deleted_at DATETIME(6) NULL, deleted_by BIGINT UNSIGNED NULL, deletion_reason VARCHAR(500) NULL, UNIQUE KEY uq_students_public_id (public_id), KEY idx_students_institution_status (institution_id, current_status), CONSTRAINT fk_students_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT, CONSTRAINT fk_students_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT fk_students_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE student_profiles (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, student_id BIGINT UNSIGNED NOT NULL, preferred_name VARCHAR(120) NULL, address TEXT NULL, notes TEXT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, deleted_at DATETIME(6) NULL, deleted_by BIGINT UNSIGNED NULL, deletion_reason VARCHAR(500) NULL, UNIQUE KEY uq_student_profiles_student (student_id), CONSTRAINT fk_student_profiles_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT, CONSTRAINT fk_student_profiles_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT fk_student_profiles_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE employees (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL, public_id CHAR(26) NOT NULL, employee_number VARCHAR(64) NOT NULL, first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120) NOT NULL, employment_status VARCHAR(32) NOT NULL, starts_on DATE NOT NULL, ends_on DATE NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, deleted_at DATETIME(6) NULL, deleted_by BIGINT UNSIGNED NULL, deletion_reason VARCHAR(500) NULL, UNIQUE KEY uq_employees_public_id (public_id), UNIQUE KEY uq_employees_number (institution_id, employee_number), UNIQUE KEY uq_employees_user (user_id), CONSTRAINT fk_employees_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT, CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT chk_employees_dates CHECK (ends_on IS NULL OR ends_on >= starts_on)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE class_assignments (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, class_id BIGINT UNSIGNED NOT NULL, employee_id BIGINT UNSIGNED NOT NULL, assignment_role VARCHAR(32) NOT NULL, starts_on DATE NOT NULL, ends_on DATE NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, UNIQUE KEY uq_class_assignments_public_id (public_id), UNIQUE KEY uq_class_assignments_period (class_id, employee_id, assignment_role, starts_on), KEY idx_class_assignments_employee (employee_id, starts_on), CONSTRAINT fk_class_assignments_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT, CONSTRAINT fk_class_assignments_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE RESTRICT, CONSTRAINT fk_class_assignments_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE RESTRICT, CONSTRAINT chk_class_assignments_dates CHECK (ends_on IS NULL OR ends_on >= starts_on)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'
        ]; foreach ($sql as $statement) { $pdo->prepare($statement)->execute(); }
    }
    public function down(PDO $pdo): void { foreach (['class_assignments','employees','student_profiles','students'] as $table) { $pdo->prepare("DROP TABLE IF EXISTS {$table}")->execute(); } }
};
