<?php

declare(strict_types=1);

use Database\MigrationInterface;
use PDO;

return new class implements MigrationInterface {
    public function version(): string { return '005'; }
    public function timestamp(): string { return '2026-07-25T00:04:00Z'; }
    public function description(): string { return 'Create guardian and relationship tables.'; }
    public function dependencies(): array { return ['004']; }
    public function up(PDO $pdo): void {
        $sql = [
            'CREATE TABLE guardians (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL, public_id CHAR(26) NOT NULL, first_name VARCHAR(120) NOT NULL, last_name VARCHAR(120) NOT NULL, national_id_hash CHAR(64) NULL, status VARCHAR(32) NOT NULL DEFAULT \'active\', created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, deleted_by BIGINT UNSIGNED NULL, deletion_reason VARCHAR(500) NULL, UNIQUE KEY uq_guardians_public_id (public_id), UNIQUE KEY uq_guardians_user (user_id), UNIQUE KEY uq_guardians_national_id_hash (national_id_hash), CONSTRAINT fk_guardians_institution FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE RESTRICT, CONSTRAINT fk_guardians_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE guardian_relationships (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, student_id BIGINT UNSIGNED NOT NULL, guardian_id BIGINT UNSIGNED NOT NULL, relationship_type VARCHAR(16) NOT NULL, other_subtype VARCHAR(32) NULL, other_description VARCHAR(160) NULL, is_legal_guardian BOOLEAN NOT NULL DEFAULT FALSE, is_pickup_authorized BOOLEAN NOT NULL DEFAULT FALSE, emergency_priority TINYINT UNSIGNED NULL, verified_at DATETIME(6) NULL, starts_on DATE NOT NULL, ends_on DATE NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, UNIQUE KEY uq_guardian_relationships_period (student_id, guardian_id, starts_on), KEY idx_guardian_relationships_guardian (guardian_id, verified_at, starts_on), CONSTRAINT fk_guardian_relationships_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT, CONSTRAINT fk_guardian_relationships_guardian FOREIGN KEY (guardian_id) REFERENCES guardians(id) ON DELETE RESTRICT, CONSTRAINT chk_guardian_relationship_type CHECK (relationship_type IN (\'Father\', \'Mother\', \'Other\')), CONSTRAINT chk_guardian_other CHECK ((relationship_type <> \'Other\') OR other_subtype IS NOT NULL OR other_description IS NOT NULL), CONSTRAINT chk_guardian_relationship_dates CHECK (ends_on IS NULL OR ends_on >= starts_on)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE guardian_contact_methods (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, guardian_id BIGINT UNSIGNED NOT NULL, type VARCHAR(16) NOT NULL, value VARCHAR(254) NOT NULL, normalized_value VARCHAR(254) NOT NULL, is_primary BOOLEAN NOT NULL DEFAULT FALSE, is_verified BOOLEAN NOT NULL DEFAULT FALSE, preference_rank TINYINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, UNIQUE KEY uq_guardian_contact_methods_value (guardian_id, type, normalized_value), CONSTRAINT fk_guardian_contact_methods_guardian FOREIGN KEY (guardian_id) REFERENCES guardians(id) ON DELETE RESTRICT, CONSTRAINT chk_guardian_contact_type CHECK (type IN (\'phone\', \'email\', \'address\'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE pickup_authorizations (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, student_id BIGINT UNSIGNED NOT NULL, guardian_id BIGINT UNSIGNED NULL, public_id CHAR(26) NOT NULL, collector_name VARCHAR(240) NOT NULL, relationship_label VARCHAR(120) NOT NULL, identity_reference_hash CHAR(64) NULL, starts_at DATETIME(6) NOT NULL, ends_at DATETIME(6) NULL, status VARCHAR(32) NOT NULL DEFAULT \'pending\', approved_by BIGINT UNSIGNED NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, deleted_by BIGINT UNSIGNED NULL, deletion_reason VARCHAR(500) NULL, UNIQUE KEY uq_pickup_authorizations_public_id (public_id), KEY idx_pickup_authorizations_active (student_id, status, starts_at, ends_at), CONSTRAINT fk_pickup_authorizations_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT, CONSTRAINT fk_pickup_authorizations_guardian FOREIGN KEY (guardian_id) REFERENCES guardians(id) ON DELETE SET NULL, CONSTRAINT fk_pickup_authorizations_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT chk_pickup_authorizations_dates CHECK (ends_at IS NULL OR ends_at > starts_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            'CREATE TABLE emergency_contacts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, student_id BIGINT UNSIGNED NOT NULL, name VARCHAR(240) NOT NULL, relationship_label VARCHAR(120) NOT NULL, phone VARCHAR(32) NOT NULL, priority TINYINT UNSIGNED NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, UNIQUE KEY uq_emergency_contacts_priority (student_id, priority), CONSTRAINT fk_emergency_contacts_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT, CONSTRAINT chk_emergency_contacts_priority CHECK (priority > 0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'
        ]; foreach ($sql as $statement) { $pdo->prepare($statement)->execute(); }
    }
    public function down(PDO $pdo): void { foreach (['emergency_contacts','pickup_authorizations','guardian_contact_methods','guardian_relationships','guardians'] as $table) { $pdo->prepare("DROP TABLE IF EXISTS {$table}")->execute(); } }
};
