<?php
declare(strict_types=1);
use Database\MigrationInterface; use PDO;
return new class implements MigrationInterface {
 public function version(): string{return '007';} public function timestamp(): string{return '2026-07-25T00:06:00Z';} public function description(): string{return 'Create attendance and QR tables.';} public function dependencies(): array{return ['006'];}
 public function up(PDO $p): void { $s=[
 'CREATE TABLE attendance_statuses (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, code VARCHAR(32) NOT NULL, name VARCHAR(100) NOT NULL, is_terminal BOOLEAN NOT NULL DEFAULT FALSE, UNIQUE KEY uq_attendance_statuses_code (code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'CREATE TABLE attendance_rules (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, institution_id BIGINT UNSIGNED NOT NULL, academic_year_id BIGINT UNSIGNED NULL, public_id CHAR(26) NOT NULL, late_after TIME NULL, lock_after_hours SMALLINT NULL, absence_alert_threshold SMALLINT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL, UNIQUE KEY uq_attendance_rules_public_id (public_id), KEY idx_attendance_rules_year (academic_year_id), CONSTRAINT fk_attendance_rules_institution FOREIGN KEY (institution_id) REFERENCES institutions(id), CONSTRAINT fk_attendance_rules_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'CREATE TABLE attendance_days (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, student_id BIGINT UNSIGNED NOT NULL, student_enrollment_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, attendance_date DATE NOT NULL, status_id BIGINT UNSIGNED NULL, finalized_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, UNIQUE KEY uq_attendance_days_public_id (public_id), UNIQUE KEY uq_attendance_days_student_date (student_id, attendance_date), KEY idx_attendance_days_enrollment_date (student_enrollment_id, attendance_date), KEY idx_attendance_days_date_status (attendance_date, status_id), CONSTRAINT fk_attendance_days_student FOREIGN KEY (student_id) REFERENCES students(id), CONSTRAINT fk_attendance_days_enrollment FOREIGN KEY (student_enrollment_id) REFERENCES student_enrollments(id), CONSTRAINT fk_attendance_days_status FOREIGN KEY (status_id) REFERENCES attendance_statuses(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'CREATE TABLE attendance_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, attendance_day_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, event_type VARCHAR(32) NOT NULL, occurred_at DATETIME(6) NOT NULL, method VARCHAR(32) NOT NULL, actor_user_id BIGINT UNSIGNED NULL, notes VARCHAR(500) NULL, created_at DATETIME(6) NOT NULL, UNIQUE KEY uq_attendance_events_public_id (public_id), KEY idx_attendance_events_day_time (attendance_day_id, occurred_at), CONSTRAINT fk_attendance_events_day FOREIGN KEY (attendance_day_id) REFERENCES attendance_days(id), CONSTRAINT fk_attendance_events_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'CREATE TABLE attendance_corrections (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, attendance_event_id BIGINT UNSIGNED NOT NULL, public_id CHAR(26) NOT NULL, requested_by BIGINT UNSIGNED NOT NULL, reason VARCHAR(500) NOT NULL, requested_at DATETIME(6) NOT NULL, approved_by BIGINT UNSIGNED NULL, approved_at DATETIME(6) NULL, outcome VARCHAR(32) NOT NULL DEFAULT \'pending\', UNIQUE KEY uq_attendance_corrections_public_id (public_id), KEY idx_attendance_corrections_event (attendance_event_id, outcome, requested_at), CONSTRAINT fk_attendance_corrections_event FOREIGN KEY (attendance_event_id) REFERENCES attendance_events(id), CONSTRAINT fk_attendance_corrections_requested FOREIGN KEY (requested_by) REFERENCES users(id), CONSTRAINT fk_attendance_corrections_approved FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'CREATE TABLE qr_tokens (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, public_id CHAR(26) NOT NULL, purpose VARCHAR(32) NOT NULL, token_hash CHAR(64) NOT NULL, nonce CHAR(26) NOT NULL, expires_at DATETIME(6) NOT NULL, issued_by BIGINT UNSIGNED NULL, invalidated_at DATETIME(6) NULL, used_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL, UNIQUE KEY uq_qr_tokens_public_id (public_id), UNIQUE KEY uq_qr_tokens_hash (token_hash), UNIQUE KEY uq_qr_tokens_nonce (nonce), KEY idx_qr_tokens_cleanup (expires_at, invalidated_at, used_at), CONSTRAINT fk_qr_tokens_issuer FOREIGN KEY (issued_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'CREATE TABLE qr_scan_attempts (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, qr_token_id BIGINT UNSIGNED NULL, public_id CHAR(26) NOT NULL, scanned_at DATETIME(6) NOT NULL, actor_user_id BIGINT UNSIGNED NULL, result VARCHAR(32) NOT NULL, failure_code VARCHAR(64) NULL, request_id CHAR(26) NULL, UNIQUE KEY uq_qr_scan_attempts_public_id (public_id), KEY idx_qr_scan_attempts_token_time (qr_token_id, scanned_at), CONSTRAINT fk_qr_scan_attempts_token FOREIGN KEY (qr_token_id) REFERENCES qr_tokens(id) ON DELETE SET NULL, CONSTRAINT fk_qr_scan_attempts_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
 'CREATE TABLE pickup_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, student_id BIGINT UNSIGNED NOT NULL, pickup_authorization_id BIGINT UNSIGNED NULL, attendance_event_id BIGINT UNSIGNED NULL, public_id CHAR(26) NOT NULL, verified_by BIGINT UNSIGNED NOT NULL, occurred_at DATETIME(6) NOT NULL, verification_method VARCHAR(32) NOT NULL, notes VARCHAR(500) NULL, UNIQUE KEY uq_pickup_events_public_id (public_id), KEY idx_pickup_events_student_time (student_id, occurred_at), CONSTRAINT fk_pickup_events_student FOREIGN KEY (student_id) REFERENCES students(id), CONSTRAINT fk_pickup_events_authorization FOREIGN KEY (pickup_authorization_id) REFERENCES pickup_authorizations(id) ON DELETE SET NULL, CONSTRAINT fk_pickup_events_event FOREIGN KEY (attendance_event_id) REFERENCES attendance_events(id) ON DELETE SET NULL, CONSTRAINT fk_pickup_events_verifier FOREIGN KEY (verified_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci']; foreach($s as $q){$p->prepare($q)->execute();}}
 public function down(PDO $p): void{foreach(['pickup_events','qr_scan_attempts','qr_tokens','attendance_corrections','attendance_events','attendance_days','attendance_rules','attendance_statuses'] as $t){$p->prepare("DROP TABLE IF EXISTS {$t}")->execute();}}
};
